### ISSUE TITLE
Should I contribute a C++11 RAII wrapper for MTBL objects?

### ISSUE THREAD

**Issue by snarkmaster** [farsightsec/mtbl#12]
I've found this wrapper useful:

```
namespace mtbl {

/**
 * RAII wrappers for mtbl_* objects. Think of these as std::unique_ptr with
 * custom constructors and deleters.  Sample usage:
 *
 *   mtbl::SorterOptions sopt;
 *   mtbl_sorter_options_set_max_memory(sopt(), 1 << 30);  // 1GB
 *   mtbl::Sorter sorter(sopt());  // Does *not* take ownership of sopt.
 */
template <
  typename PtrT,
  typename InitFuncT,
  InitFuncT initFunc,
  typename DestroyFuncT,
  DestroyFuncT destroyFunc
>
class MtblPtr : boost::noncopyable {
public:
  using type = MtblPtr<PtrT, InitFuncT, initFunc, DestroyFuncT, destroyFunc>;

  template <typename... Args>
  MtblPtr(Args&&... args) : p_(initFunc(std::forward<Args>(args)...)) {
    if (p_ == nullptr) {
      throw std::bad_alloc();
    }
  }  
  ~MtblPtr() { reset(nullptr); }

  // Movable
  MtblPtr(type&& m) : p_(m.p_) { m.p_ = nullptr; }
  type& operator=(type&& m) {
    reset(m.p_);
    m.p_ = nullptr;
  }

  PtrT operator()() { return p_; }

  PtrT release() {
    auto res = p_;
    p_ = nullptr; 
    return res;   
  }

  void reset(PtrT ptr) {
    if (p_ != nullptr) {  // Redundant, since mtbl checks this too
      destroyFunc(&p_);
    }
    p_ = ptr;
  }

private:
  PtrT p_;
};

// These were made by searching for '_init(' in mtbl.h:

typedef MtblPtr<
  mtbl_iter*,   
  decltype(&mtbl_iter_init),
  &mtbl_iter_init,  
  decltype(&mtbl_iter_destroy),
  &mtbl_iter_destroy 
> Iter;

typedef MtblPtr<
  mtbl_source*, 
  decltype(&mtbl_source_init),
  &mtbl_source_init,  
  decltype(&mtbl_source_destroy),
  &mtbl_source_destroy 
> Source;

...
```

Are you interested in including this as, e.g. `mtbl.hpp`?

**Comment by snarkmaster** [comment]
(Obviously, I would lose the dependency on `boost::noncopyable`.)

**Comment by snarkmaster** [comment]
Don't read the above code too closely -- it has seen many changes.

**Comment by edmonds** [comment]
Hm, in general I'm a fan of keeping library binding separate from the library itself, so e.g., `mtbl` (containing the C library) and `pymtbl` (containing the Python bindings for the C library) are kept in separate repositories. So I'd recommend to put this in its own repository. (We don't do much if any C++ work here, so I doubt this is something we'd want to maintain under the `farsightsec` GitHub org.)

If you're interested in maintaining it in your own repo, I'd be happy to add a section for links to bindings in the `README.md` file, though!

**Comment by snarkmaster** [comment]
I see. I made the wrapper a lot shorter -- presently, it's 76 lines (plus 30 lines of unit test). It's no biggie to put it in a separate repo, though. I'll comment here when I've put it up, and would be grateful if you mention it in the README.md.
