### ISSUE TITLE
mtbl_verify periodic progress always 0 blocks / 0%

### ISSUE THREAD

**Issue by reedjc** [farsightsec/mtbl#48]
0 out of ... blocks (0.00%) for mtbl_verify periodic progress doesn't make sense.

I ran it on 36 files with real data and verify said is OK but progress always is zero.

The manpage is too brief about it.

**Comment by reedjc** [comment]
I see what the "0" is from. The periodic progress is shown once every 10,000 blocks. .... if ((block % block_progress_interval) == 0) {

The blocks count starts at 0, so the first progress report happens at 0.
So I was looking at many MTBL files that had less than 10,000 blocks.
I think for last (or only) blocks it should have real count like:

dns.20190403.1733.m.mtbl: 43,629 out of 43,629 blocks (100.00%) OK

As it is now, the "0 out of 1 blocks (0.00%) OK" or"0 out of 4 blocks (0.00%) OK" (whatever is less than the 10,000) never makes sense.

**Comment by reedjc** [comment]
I made a branch to clean this up.

**Comment by cmikk** [comment]
Fix was merged in https://github.com/farsightsec/mtbl/commit/baa09dcda6a5a6c5a5b93902912ed43f30db5955
