### ISSUE TITLE
Question about the minimum block length

### ISSUE THREAD

**Issue by Kerollmops** [farsightsec/mtbl#55]
Through my adventure [on re-implementing MTBL in Rust](https://github.com/Kerollmops/oxidized-mtbl) I found a strange hard written value, the minimum sized block length. My program crashed when I keep using the 4 fixed-length 32-bit integers (16 bytes) so I computed it by myself and found out that, now that MTBL V2 uses varints, the minimum sized block length is 13 bytes.

I am maybe missing something somewhere.

https://github.com/farsightsec/mtbl/blob/bbfd07dd37ff0be8661eca4c1267c65047566a65/mtbl/reader.c#L171-L178

```
compressed block (8)
block length varint encoded (1)
crc (4)
bytes written (13)
```

**Comment by cmikk** [comment]
This is a good catch, and thank you.

We will fix this in our next release.
