### ISSUE TITLE
Maybe an overflow bug in the bytes_shortest_separator function

### ISSUE THREAD

**Issue by Kerollmops** [farsightsec/mtbl#56]
https://github.com/farsightsec/mtbl/blob/ed545dc61f8226a359788d6f85badf1de8501c03/mtbl/bytes.h#L25

I find out that `min_length` can be smaller than `sizeof(uint16_t)` and therefore an overflow happens when we do the substraction. I fixed this bug by using [a `saturating_sub` in my Rust port](https://github.com/Kerollmops/oxidized-mtbl/blob/a2e13cba5fb3ed606d2a18a43260c5487eb38746/src/writer.rs#L254) but I think a simple rewrite can do the job in C too.

```c
else if (min_length >= sizeof(uint16_t) && diff_index < min_length - sizeof(uint16_t))
```

Now that I found and fixed the bug on my side I can go play to Hades again 😄

**Comment by cmikk** [comment]
Fix is merged into next. Thanks!
