### ISSUE TITLE
Did the release for 1.6.0 change?

### ISSUE THREAD

**Issue by SMillerDev** [farsightsec/mtbl#80]
When Homebrew first added this release it had the checksum
`6563ddf1c7d9973efa7c58033fd339e68e19be69a234fa5a25448871704942df` but now the download checksums as `18ed7c9bb8b5ae71decd47dc7c882d1d6a63b61fd679a65b5f526fc241fd76f2` is something malicious going on? Or was the release retagged? Because the [git manual](https://git-scm.com/docs/git-tag#_on_re_tagging) says re-tagging is "the insane thing" to do.

**Comment by reedjc** [comment]
You may be correct that the public release was re-tagged. We should not do that. We may spin a new release to fix this.
We will research this.  I don't have the previous download file to compare with.

**Comment by mcrawforddt** [comment]
v1.6.1 is now available. The original v1.6.0 is also restored. The mistakenly uploaded one is available as https://dl.farsightsecurity.com/dist/mtbl/mtbl-1.6.0.tar.gz.mistake (sha25sum 18ed7c9bb8b5ae71decd47dc7c882d1d6a63b61fd679a65b5f526fc241fd76f2) if that is needed for anything.
