### ISSUE TITLE
missing build files for mtbl-1.7.0.tar.gz

### ISSUE THREAD

**Issue by chenrui333** [farsightsec/mtbl#87]
👋 for the 1.7.0 release, there are  several essential build files are missing. These files include but are not limited to:

- configure
- Makefile.in
- Files from build-aux/, such as config.guess, config.sub, etc.

let me know if that makes sense, ,thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/199937

**Comment by mcrawforddt** [comment]
Thanks, I'll take a look and get that fixed.

**Comment by mcrawforddt** [comment]
Version 1.7.1 has been released with an updated tarball. I have verified the presence of those files in this version. Please let me know if this does not resolve the issue.
https://github.com/farsightsec/mtbl/releases/tag/tags%2Fv1.7.1

**Comment by chenrui333** [comment]
sounds good, testing the new release in https://github.com/Homebrew/homebrew-core/pull/200088

**Comment by chenrui333** [comment]
just checked it out in my local, builds out fine. Thanks!!
